### PR TITLE
update gnome blur provider

### PR DESCRIPTION
**Pull request by CorvetteCole**
This PR should be merged once https://github.com/aunetx/blur-my-shell/pull/39 is merged (soon) to ensure documentation accuracy. I will leave a comment when it is

### CODE REVIEW

**Comment by aunetx** [comment]
It looks like aunetx/blur-my-shell#180 will make this incompatible with gnome; would it be better for me to provide a fallback so this works anyway?

`blur-provider=sigma:30,brightness:0.8` would now work, but `blur-provider=30` too, as a way not to break already existing applications; however this should be changed to the most recent API here.

**Comment by NyaomiDEV** [comment]
I am not available to change the GNOME API as I don't really have a GNOME setup to test; since Cole is already making a pull request, it'd be wise to use it also to support Blur My Shell directly.

Side note, Glasstron doesn't support Wayland; now would that be a problem for GNOME since it's already using Wayland first? If so, it'd be better to hold off any real changes to Glasstron until we find a way to talk to compositors under Wayland (which is the real problem here, and I don't know how to make this into reality).

I think that Glasstron is dying anyway because of Wayland growing and becoming more usable day after day.

**Comment by CorvetteCole** [comment]
I actually tested glasstron on Wayland gnome and it seemed to work so that's interesting. I'll send a screenshot later on

**Comment by NyaomiDEV** [comment]
> I actually tested glasstron on Wayland gnome and it seemed to work so that's interesting. I'll send a screenshot later on

Electron applications run on XWayland for now. Once they switch to be native Wayland clients, Glasstron will no longer work. For now we're just playing the "X11 in a sandbox" game.

**Comment by CorvetteCole** [comment]
these mutter hints actually work on Wayland, so there's a fair chance we can keep using them. at least on gnome. I'll have to investigate it

**Comment by NyaomiDEV** [comment]
> these mutter hints actually work on Wayland, so there's a fair chance we can keep using them. at least on gnome. I'll have to investigate it

The Mutter hints are stored in an X window property that XWayland passes on to the Wayland compositor so that it can process them. Once XWayland is out of the picture, Glasstron will break since there's no way to assign window properties from our end on native Wayland.

**Comment by KorbsStudio** [comment]
> I will drop this project once there are official ways of getting Acrylic and Mica on Windows.

I've been meaning to find a way to get Mica to work in Glasstron, but haven't had any luck. Also my Windows 11 install eventfully broke because, well...it's Windows 11.

**Comment by NyaomiDEV** [comment]
> I've been meaning to find a way to get Mica to work in Glasstron, but haven't had any luck. Also my Windows 11 install eventfully broke because, well...it's Windows 11.

I mean.. it is doable, just you'd need to be using insider builds and undocumented APIs as far as I am aware of; but we're talking of things beyond this PR's scope.

**Pull request merged**
